name: Deploy to GCP Dev

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: tikninja-app-dev
  REGION: ${{ secrets.GCP_LOCATION }}
  REGISTRY_REPO_NAME: tikninja-app-dev
  REGISTRY_NAME: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker ${{ env.REGISTRY_NAME }} --quiet

      - name: Create .env file
        run: |
          rm -f .env  # Remove .env if it exists
          echo "GCP_PROJECT_ID=${{ env.PROJECT_ID }}" >> .env
          echo "GCP_REGION=${{ env.REGION }}" >> .env
          echo "VIDEO_PROCESSING_TOPIC=${{ vars.VIDEO_PROCESSING_TOPIC }}" >> .env
          echo "OPENAI_API_KEY=${{ vars.OPENAI_API_KEY }}" >> .env
          echo "PEXELS_API_KEY=${{ vars.PEXELS_API_KEY }}" >> .env

      - name: Build and Push Docker image
        run: |
          IMAGE_URI=$REGISTRY_NAME/$PROJECT_ID/$REGISTRY_REPO_NAME/$IMAGE_NAME:$GITHUB_SHA
          docker build -t $IMAGE_URI .
          docker tag $IMAGE_URI $REGISTRY_NAME/$PROJECT_ID/$REGISTRY_REPO_NAME/$IMAGE_NAME:latest
          docker push $REGISTRY_NAME/$PROJECT_ID/$REGISTRY_REPO_NAME/$IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URI=$REGISTRY_NAME/$PROJECT_ID/$REGISTRY_REPO_NAME/$IMAGE_NAME:latest
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image $IMAGE_URI \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 3000 \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 1 \
            --service-account ${{ secrets.GCP_PROJECT_SA_NAME }}
             --revision-limit 2

      - name: Set IAM Policy Binding
        run: |
          gcloud run services add-iam-policy-binding ${{ env.IMAGE_NAME }} \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region ${{ env.REGION }}
