name: Deploy to GCP Dev

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  REGION: ${{ secrets.GCP_LOCATION }}
  REGISTRY_NAME: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev
  REGISTRY_APP_REPO_NAME: tikninja-app-dev
  APP_IMAGE_NAME: tikninja-app-dev
  REGISTRY_WORKER_REPO_NAME: tikninja-worker-dev
  WORKER_IMAGE_NAME: tikninja-worker-dev
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker ${{ env.REGISTRY_NAME }} --quiet

      - name: Create .env file
        run: |
          rm -rf .env  # Remove .env if it exists
          echo "GCP_PROJECT_ID=${{ env.PROJECT_ID }}" >> ./apps/app/.env
          echo "GCP_REGION=${{ env.REGION }}" >> ./apps/app/.env
          echo "VIDEO_PROCESSING_TOPIC=${{ vars.VIDEO_PROCESSING_TOPIC }}" >> ./apps/app/.env
          echo "OPENAI_API_KEY=${{ vars.OPENAI_API_KEY }}" >> ./apps/app/.env
          echo "PEXELS_API_KEY=${{ vars.PEXELS_API_KEY }}" >> ./apps/app/.env
          echo "CS_BUCKET_NAME=${{ vars.CS_BUCKET_NAME }}" >> ./apps/app/.env

      - name: Copy same app/.env file to worker
        run: |
          cp ./apps/app/.env ./apps/worker/.env

      - name: Build and Push App Docker image
        run: |
          IMAGE_URI=$REGISTRY_NAME/$PROJECT_ID/$REGISTRY_APP_REPO_NAME/$APP_IMAGE_NAME:$GITHUB_SHA
          docker build -f ./docker/NextJSDockerfile -t $IMAGE_URI .
          docker tag $IMAGE_URI $REGISTRY_NAME/$PROJECT_ID/$REGISTRY_APP_REPO_NAME/$APP_IMAGE_NAME:latest
          docker push $REGISTRY_NAME/$PROJECT_ID/$REGISTRY_APP_REPO_NAME/$APP_IMAGE_NAME:latest

      - name: Build and Push Worker Docker image
        run: |
          IMAGE_URI=$REGISTRY_NAME/$PROJECT_ID/$REGISTRY_WORKER_REPO_NAME/$WORKER_IMAGE_NAME:$GITHUB_SHA
          docker build -f ./docker/WorkerDockerfile -t $IMAGE_URI .
          docker tag $IMAGE_URI $REGISTRY_NAME/$PROJECT_ID/$REGISTRY_WORKER_REPO_NAME/$WORKER_IMAGE_NAME:latest
          docker push $REGISTRY_NAME/$PROJECT_ID/$REGISTRY_WORKER_REPO_NAME/$WORKER_IMAGE_NAME:latest

      - name: Create Worker to Cloud Run Job
        run: |
          WORKER_IMAGE_URI=$REGISTRY_NAME/$PROJECT_ID/$REGISTRY_WORKER_REPO_NAME/$WORKER_IMAGE_NAME:latest
          gcloud beta run jobs deploy ${{ env.WORKER_IMAGE_NAME }} \
            --image $WORKER_IMAGE_URI \
            --region ${{ env.REGION }} \
            --tasks 3 \
            --memory 2048Mi \
            --cpu 2 \
            --max-retries 3 \
            --task-timeout 3600s \
            --service-account ${{ secrets.GCP_PROJECT_SA_NAME }} \
            --set-env-vars "NODE_ENV=production" \
            --quiet

      - name: Deploy App to Cloud Run
        run: |
          IMAGE_URI=$REGISTRY_NAME/$PROJECT_ID/$REGISTRY_APP_REPO_NAME/$APP_IMAGE_NAME:latest
          gcloud run deploy ${{ env.APP_IMAGE_NAME }} \
            --image $IMAGE_URI \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 3000 \
             --memory 512Mi \
            --cpu 1 \
            --max-instances 1 \
            --timeout 3600 \
            --service-account ${{ secrets.GCP_PROJECT_SA_NAME }}

      - name: Set IAM Policy Binding
        run: |
          gcloud run services add-iam-policy-binding ${{ env.APP_IMAGE_NAME }} \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region ${{ env.REGION }}
